sudo: true
dist: trusty
language: node_js
node_js:
  - "8"
  - "10"
  - "11"

branches:
  only:
    - master

cache: npm

services:
  - mysql
  
before_install:
  - mysql -u root < test/sql/world.sql

install:
  - npm install

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

script:
  - npm run test
      
stages:
  - test
