sudo: true
dist: xenial
services:
  - mysql
language: node_js
node_js:
  - "8"
  - "10"
  - "11"

branches:
  only:
    - master

cache: npm

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS world;"
  - mysql -e "set GLOBAL max_connections=2000;"
  - mysql -e "set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';"
  - mysql -e "set session sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';"

install:
  - npm install
  - npm install --save-dev

before_script:
  - mysql -u root world < test/sql/world.sql

script:
  - npm run coverage

stages:
  - test
