sudo: true
dist: trusty
services:
  - mysql
language: node_js
node_js:
  - "8"
  - "10"
  - "11"

branches:
  only:
    - master

cache: npm

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS world;"
  - mysql -e "CREATE USER 'majo'@'localhost';"
  - mysql -e "GRANT ALL ON *.* TO 'majo'@'localhost';"
  - mysql -e "FLUSH PRIVILEGES;"

install:
  - npm install

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_script:
  - mysql -u root world < test/sql/world.sql
  
script:
  - npm run test
      
stages:
  - test
